"""describe the schema change

Revision ID: 3a1039209bd8
Revises: aaf8f5c31fc6
Create Date: 2026-09-18 16:47:55.365800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a1039209bd8'
down_revision: Union[str, Sequence[str], None] = 'aaf8f5c31fc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=2048), nullable=False),
    sa.Column('min_players', sa.Integer(), nullable=False),
    sa.Column('max_players', sa.Integer(), nullable=False),
    sa.Column('min_play_time', sa.Integer(), nullable=False),
    sa.Column('max_play_time', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('game_insight',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('total_reviews', sa.Integer(), nullable=False),
    sa.Column('average_rating', sa.Float(), nullable=False),
    sa.Column('positive_percentage', sa.Float(), nullable=False),
    sa.Column('neutral_percentage', sa.Float(), nullable=False),
    sa.Column('negative_percentage', sa.Float(), nullable=False),
    sa.Column('easy_percentage', sa.Float(), nullable=False),
    sa.Column('medium_percentage', sa.Float(), nullable=False),
    sa.Column('hard_percentage', sa.Float(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_insight_complaint',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('game_insight_id', sa.Uuid(), nullable=False),
    sa.Column('complaint', sa.String(length=255), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['game_insight_id'], ['game_insight.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_insight_liked_aspect',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('game_insight_id', sa.Uuid(), nullable=False),
    sa.Column('aspect', sa.String(length=255), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['game_insight_id'], ['game_insight.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_analysis',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('review_id', sa.Uuid(), nullable=False),
    sa.Column('sentiment', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('perceived_difficulty', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['review.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_id')
    )
    op.create_table('review_complaint',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('review_analysis_id', sa.Uuid(), nullable=False),
    sa.Column('complaint', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['review_analysis_id'], ['review_analysis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_liked_aspect',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('review_analysis_id', sa.Uuid(), nullable=False),
    sa.Column('aspect', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['review_analysis_id'], ['review_analysis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table("common_complaints")
    op.drop_table("liked_aspects")
    op.drop_table("game_analysis")
    op.drop_table("reviews")
    op.drop_table("games")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('common_complaints',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('game_analysis_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('complaint', sa.VARCHAR(length=500, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['game_analysis_id'], ['game_analysis.id'], name=op.f('FK__common_co__game___4222D4EF')),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__common_c__3213E83F95B6FD84'))
    )
    op.create_table('game_analysis',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('review_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('positive_sentiment', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=False),
    sa.Column('neutral_sentiment', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=False),
    sa.Column('negative_sentiment', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=False),
    sa.Column('perceived_difficulty', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('FK__game_anal__game___3C69FB99')),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__game_ana__3213E83F3387D00C'))
    )
    op.create_table('liked_aspects',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('game_analysis_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('aspect', sa.VARCHAR(length=500, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['game_analysis_id'], ['game_analysis.id'], name=op.f('FK__liked_asp__game___44FF419A')),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__liked_as__3213E83F2F715DD8'))
    )
    op.create_table('reviews',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('FK__reviews__game_id__3F466844')),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__reviews__3213E83FCDE053D7'))
    )
    op.create_table('games',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__games__3213E83F2327FFA3'))
    )
    op.drop_table('review_liked_aspect')
    op.drop_table('review_complaint')
    op.drop_table('review_analysis')
    op.drop_table('game_insight_liked_aspect')
    op.drop_table('game_insight_complaint')
    op.drop_table('review')
    op.drop_table('game_insight')
    op.drop_table('user')
    op.drop_table('game')
    # ### end Alembic commands ###
