"""create game tables

Revision ID: aaf8f5c31fc6
Revises: 
Create Date: 2026-09-16 15:55:31.761715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaf8f5c31fc6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('game_analysis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('positive_sentiment', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('neutral_sentiment', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('negative_sentiment', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('perceived_difficulty', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('common_complaints',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_analysis_id', sa.Integer(), nullable=False),
    sa.Column('complaint', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['game_analysis_id'], ['game_analysis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('liked_aspects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_analysis_id', sa.Integer(), nullable=False),
    sa.Column('aspect', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['game_analysis_id'], ['game_analysis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('liked_aspects')
    op.drop_table('common_complaints')
    op.drop_table('reviews')
    op.drop_table('game_analysis')
    op.drop_table('games')
    # ### end Alembic commands ###
